#!/bin/sh
. /usr/local/share/my_init/functions.sh

: ${bind_forwarders:=}

# set normal umask
umask 022

cat >/var/bind/zones.conf <<EOF
zone "." {
  $(if [ -n "$bind_forwarders" ]; then
    echo "type forward;"
    echo "  forwarders {"
    for forwarder in $bind_forwarders; do
      echo "    $forwarder;"
    done
    echo "  };"
  else
    echo "type hint;"
    echo "  file \"/etc/bind/db.root\";"
  fi)
};

zone "localhost" {
  type master;
  file "/etc/bind/db.localhost";
};

zone "127.in-addr.arpa" {
  type master;
  file "/etc/bind/db.127";
};
EOF
