#!/bin/sh

: ${bind_networks:="$(ip route show | awk '$1 != "default" { print $1";" }')"}

rndc-confgen -a -r /dev/urandom -u named

# set normal umask
umask 0022

cat > /etc/bind/named.conf <<EOF
options {
    directory "/var/bind";
    pid-file "/var/run/named/named.pid";
    allow-recursion { 127.0.0.0/8; $bind_networks };
    allow-transfer { none; };
    listen-on-v6 { none; };
    dnssec-enable yes;
    dnssec-validation auto;
};

include "/etc/bind/rndc.key";

controls {
    inet 127.0.0.1 port 953
        allow { 127.0.0.1; } keys { "rndc-key"; };
};

logging {
  category default { default_syslog; };
  category general { default_syslog; };
  category database { default_syslog; };
  category security { default_syslog; };
  category config { default_syslog; };
  category resolver { default_syslog; };
  category xfer-in { default_syslog; };
  category xfer-out { default_syslog; };
  category notify { default_syslog; };
  category client { default_syslog; };
  category unmatched { default_syslog; };
  category queries { default_syslog; };
  category network { default_syslog; };
  category update { default_syslog; };
  category dispatch { default_syslog; };
  category dnssec { default_syslog; };
  category lame-servers { default_syslog; };
};

zone "." IN {
        type hint;
        file "named.ca";
};

zone "localhost" IN {
        type master;
        file "pri/localhost.zone";
        allow-update { none; };
        notify no;
};

zone "127.in-addr.arpa" IN {
        type master;
        file "pri/127.zone";
        allow-update { none; };
        notify no;
};
EOF
